database:
  host: localhost
  port: 5434
  user: postgres
  password: postgres
  name: postgres

logging:
  log_dir: logs
  level: INFO
  file: etl.log
  format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
  console: true

etl:
  extract_path: "data/input/"
  output_path: "data/output/"
  api_url: "https://example.com/data"
